### ISSUE TITLE
Website redirection

### ISSUE THREAD

**Issue by damithc** [chrystalquek/ip#5]
@chrystalquek Your ip website seems to be redirecting to chrystalquek.me which is not loading at the moment. Can remove the redirection?

**Comment by chrystalquek** [comment]
@damithc I am not sure how to check this redirection, where did you see this redirection and how should I go about changing it?

**Comment by damithc** [comment]
http://chrystalquek.github.io/ redirects to http://chrystalquek.me  which means http://chrystalquek.github.io/ip (our ip website) will be redirecting to http://chrystalquek.me/ip
http://chrystalquek.me wasn't loading y'day, but seems to be loading today.

**Comment by chrystalquek** [comment]
Removed website redirection.
